name: 定时签到任务

on:
  schedule:
    # 每天 UTC 时间晚上 11:00（北京时间早上 8:00）运行一次
    - cron: "0 0 * * *"
  
  workflow_dispatch:  # 添加手动触发器

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: '18' # 使用 Node.js 18 版本

    - name: 安装依赖并执行签到脚本（带重试）
      uses: andresz1/retry@v2  # 使用重试的 Action
      with:
        timeout_seconds: 10     # 重试间隔时间（秒）
        max_attempts: 3         # 最大重试次数
        command: |
          npm install -g pnpm
          pnpm install
          node index.js
      env:
        QYWX_ROBOT: ${{ secrets.QYWX_ROBOT }}
